spring.application.name=finanzas-peru-ws
server.port=8099

# CXF - Ruta base del servlet SOAP
cxf.path=/ws

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FinanzasPeruDB;encrypt=false;trustServerCertificate=true
spring.datasource.username=user_demo
spring.datasource.password=user_demo
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.finanzasperu=DEBUG
logging.level.org.apache.cxf=WARN

