spring.application.name=soap-service-cxf
server.port=8093

# --- Apache CXF ---
# Ruta base del CXFServlet (por defecto es /services)
cxf.path=/ws

# --- SQL Server ---
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TiendaDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=user_demo
spring.datasource.password=user_demo

# --- JPA ---
# Las tablas se crean con database/script.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
